name: Build Filters

on:
  schedule:
  - cron: "0 3 * * *"
  # For manual run builds
  workflow_dispatch:
  push:
    paths-ignore:
      # do not trigger build on changes to the following files.
      # it is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - 'optimization_config.json'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      # TODO: add a separate workflow for linting
      - name: Lint code
        run: yarn lint

      - name: Build DNS Filter
        run: TLS=insecure yarn build -i=15

      - name: Build Adblock Filters
        run: TLS=insecure yarn build -i=101,118
        # run: TLS=insecure yarn build -i=12,5,101

      - name: Push to repository
        run: |
          git config --global user.name "pkrayzy"
          git config --global user.email "pkrayzy@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Update Filters on $now"
          git push
